module.exports = [{
    genTitle: '일상',
    img: './img/lank/top-lan01.jpg',
    title: '일상의 하루',
    gen: '일상',
    name: '쿠크다',
    title2: '랄라',
    gen2: '라라',
    img2: './img/lank/top-lan02.jpg',
    title3: '루루',
    gen3: '레레',
    img3: './img/lank/top-lan03.jpg',
    title4: '라라',
    gen4: '리리',
    img4: './img/lank/top-lan04.jpg',
    title5: '로로',
    gen5: '레레',
    img5: './img/lank/top-lan05.jpg'
}, {
    genTitle: '일상',
    img: './img/lank/top-pan01.jpg',
    title: '일상의 하루',
    gen: '일상',
    name: '쿠크다',
    title2: '랄라',
    gen2: '라라',
    img2: './img/lank/top-pan02.jpg',
    title3: '루루',
    gen3: '레레',
    img3: './img/lank/top-pan03.jpg',
    title4: '라라',
    gen4: '리리',
    img4: './img/lank/top-pan04.jpg',
    title5: '로로',
    gen5: '레레',
    img5: './img/lank/top-pan05.jpg'
}, {
    genTitle: '일상',
    img: './img/lank/top-tan01.jpg',
    title: '일상의 하루',
    gen: '일상',
    name: '쿠크다',
    title2: '랄라',
    gen2: '라라',
    img2: './img/lank/top-tan02.jpg',
    title3: '루루',
    gen3: '레레',
    img3: './img/lank/top-tan03.jpg',
    title4: '라라',
    gen4: '리리',
    img4: './img/lank/top-tan04.jpg',
    title5: '로로',
    gen5: '레레',
    img5: './img/lank/top-tan05.jpg'
}];